#name: Deploy to AWS EC2
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#
#    - name: Set up SSH
#      uses: webfactory/ssh-agent@v0.5.3
#      with:
#        ssh-private-key: ${{ secrets.AWS_EC2_KEY }}
#
#    - name: Deploy to EC2
#      env:
#        HOST: ${{ secrets.AWS_EC2_HOST }}
#        USER: ${{ secrets.AWS_EC2_USER }}
#      run: |
#        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
#          cd /home/ubuntu
#          docker-compose down
#          docker-compose up -d
#        EOF
